default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        name: Check for added large files
      - id: check-toml
        name: Check Toml
      - id: check-yaml
        name: Check Yaml
      - id: end-of-file-fixer
        name: Fix End of Files
      - id: trailing-whitespace
        name: Trim Trailing Whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 6e24ff01ab7d5e64045599b81c4cd34d6a6a7159
    hooks:
      - id: prettier
