[tool.poetry]
name = "modular-auto-graphql-api"
version = "0.1.0"
description = ""
authors = ["Vojtěch Dohnal <dohnal@ics.muni.cz>"]

[tool.poetry.dependencies]
python = "^3.9"
strawberry-graphql = "^0.76.1"
inflection = "^0.5.1"
starlette = "^0.16.0"
uvicorn = {extras = ["standard"], version = "^0.15.0"}
SQLAlchemy = "^1.4.23"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
